### ISSUE TITLE
Extension causes Bitwig to open two new projects instead of one

### ISSUE THREAD

**Issue by DenisNedl** [ensonic/bitwig-timecalc#4]
If this extension is active, then Bitwig opens up one additional empty project.
This only happens after starting Bitwig and opening an existing or new project.
When closing all projects and opening a new, then only one is opened.

**Comment by ensonic** [comment]
Thanks for reporting. I saw that too, but did not realize it might me my extension. Let me take a look.

**Comment by ensonic** [comment]
Meh, updating the values in the panel causes Bitwig to mark the song as 'changed'.

**Comment by ensonic** [comment]
I am trying an idea: I'll defer setting the values if project has not already been changed. Maybe also check the project title - if "New <nr>", then wait for it to be changed.
